import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useCameraContext } from "../context/CameraContext";

const cam1 = process.env.NEXT_PUBLIC_HUALAI_CHANNEL_CAM1;
const cam2 = process.env.NEXT_PUBLIC_HUALAI_CHANNEL_CAM2;
const cam3 = process.env.NEXT_PUBLIC_HUALAI_CHANNEL_CAM3;
const cam4 = process.env.NEXT_PUBLIC_HUALAI_CHANNEL_CAM4;

const Home: NextPage = () => {
  const { cameras, selectCamera, videoRef, viewCamWithCredentials } =
    useCameraContext();

  useEffect(() => {
    if (cameras.length) console.log("Cámaras: ", cameras);
  }, [cameras]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>WebRTC Demo</h1>
        {cameras.length ? (
          <div>
            {cameras.map((camera, idx) => (
              <button key={idx} onClick={() => selectCamera(camera.mac)}>
                {camera.nickname} ({camera.conn_state ? "On" : "Off"})
              </button>
            ))}
          </div>
        ) : (
          <p>Cargando lista de camaras...</p>
        )}
        <div className="video-container">
          <video
            ref={videoRef}
            className="remote-view"
            autoPlay
            playsInline
            controls
            muted
          />
        </div>
        <p>Camaras usando AWS ID y Secret</p>
        <div>
          <button onClick={() => viewCamWithCredentials(cam1)}>
            Ver camara 1 (Con AWSID)
          </button>
          <button onClick={() => viewCamWithCredentials(cam2)}>
            Ver camara 2 (Con AWSID)
          </button>
          <button onClick={() => viewCamWithCredentials(cam3)}>
            Ver camara 3 (Con AWSID)
          </button>
          <button onClick={() => viewCamWithCredentials(cam4)}>
            Ver camara 4 (Con AWSID)
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
