import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useCameraContext } from "../context/CameraContext";

const Home: NextPage = () => {
  const { cameras, selectCamera, videoRef } = useCameraContext();

  useEffect(() => {
    if (cameras.length) console.log("Cámaras: ", cameras);
  }, [cameras]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>WebRTC Demo</h1>
        {cameras.length ? (
          <div>
            {cameras.map((camera, idx) => (
              <button key={idx} onClick={() => selectCamera(camera.mac)}>
                {camera.nickname} ({camera.conn_state ? "On" : "Off"})
              </button>
            ))}
          </div>
        ) : (
          <p>Cargando lista de camaras...</p>
        )}
        <div className="video-container">
          <video
            ref={videoRef}
            className="remote-view"
            autoPlay
            playsInline
            controls
            muted
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
